### PR TITLE
✨ Add Feature Prisma as database option

### PR DESCRIPTION
**Pull request by craigharman**
## What(무엇을 변경하셨나요 ?)

Added [Prisma](https://www.prisma.io/) as a database option.

## Why(왜 변경하셨나요 ?)

Give people the option to use Prisma as an ORM/Query Builder.

## How(어떻게 변경하였나요 ?)

Duplicated the /default folder and then added in the changes required to use Prisma instead.

## Check List(체크 사항)

- [ ] Issue(이슈)
- [X] Tests(테스트)
- [X] Ready to be merged(병합 준비 완료)
      
- [X] Added myself to contributors table(기여자 추가)

### CODE REVIEW

**Comment by ljlm0402** [comment]
@craigharman 

Thank you very much for your pull request.

**Comment by ljlm0402** [comment]
@craigharman 

image

Do you have a solution for this error?

**Comment by craigharman** [comment]
Have you run `prisma generate`?

If not, try that first. Otherwise, let me know the steps to recreate and I
will take a look for you.

Craig

**Comment by ljlm0402** [comment]
@craigharman 

I have run `npm run generate(prisma generate)`
and `npm run dev` 

-> Invalid `prisma.user.findMany()` invocation:

image

**Comment by craigharman** [comment]
Make sure you are running a docker container for the database (eg. mysql
and the configuration string is correct) You will also need to run the
migrations. This will create the tables.

prisma migrate dev --preview-feature

Once this is done it should work.

Perhaps these steps can be added the readme? I jsut couldn't find a good
place to put them in the PR. Hopefully you can also add the prisma logo to
the image in the readme.md?

**Comment by ljlm0402** [comment]
@craigharman 

I will modify the README.md.
Thanks for the help.

**Comment by craigharman** [comment]
Awesome, thanks!

**Comment by ljlm0402** [comment]
@craigharman 

auth.middleware > req.user missing the following properties
image

We are solving the issue, is there a good way?

**Comment by craigharman** [comment]
I missed that!

Delete user.interface.ts

In auth.interface.ts

Try replacing:

import { User } from './users.interface';

with

import { User } from ***@***.***/client';

**Pull request merged**
